version: 2
jobs:
  build:
    working_directory: ~/lonely
    docker:
      - image: trenpixster/elixir:1.4.4
    steps:
      - checkout
      - run: mix deps.get
      - run: mix test
      - run: mix check
